window.DEVFUSION_SITE = {
  email: "devfusionorg@gmail.com",
  stats: [
    { value: "2", label: "core members" },
    { value: "3", label: "public projects" },
    { value: "AI / ML / DL", label: "specialization" },
  ],
  services: [
    {
      title: "AI and ML solutions",
      text: "Model development, preprocessing pipelines, and practical deployment-ready interfaces.",
    },
    {
      title: "Deep learning prototypes",
      text: "Image classification, predictive systems, and experiment-driven product implementations.",
    },
    {
      title: "Software, Android, and web builds",
      text: "Hackathon MVPs and practice projects with clean product UI and reliable feature delivery.",
    },
  ],
  tech: [
    { name: "Python", symbol: "PY", icon: "🐍", tone: "teal" },
    { name: "Machine Learning", symbol: "ML", icon: "🤖", tone: "blue" },
    { name: "Deep Learning", symbol: "DL", icon: "🧠", tone: "orange" },
    { name: "EDA", symbol: "EDA", icon: "🔎", tone: "teal" },
    { name: "TensorFlow", symbol: "TF", icon: "📊", tone: "blue" },
    { name: "Scikit-Learn", symbol: "SK", icon: "📈", tone: "teal" },
    { name: "OpenCV", symbol: "CV", icon: "👁", tone: "orange" },
    { name: "NLP", symbol: "NLP", icon: "💬", tone: "blue" },
    { name: "FastAPI", symbol: "API", icon: "⚡", tone: "teal" },
    { name: "Docker", symbol: "DK", icon: "🐳", tone: "orange" },
    { name: "Android", symbol: "AD", icon: "🤳", tone: "blue" },
    { name: "Web Development", symbol: "WEB", icon: "🌐", tone: "teal" },
    { name: "MySQL", symbol: "SQL", icon: "🗃", tone: "orange" },
  ],
  members: [
    {
      name: "Dushyant",
      role: "Developer",
      image: "d.png",
      email: "dushyantrajotia@gmail.com",
      phone: "+91 9416978967",
      linkedin: "https://www.linkedin.com/in/dushyantrajotia/",
      github: "https://github.com/dushyantrajotia",
      portfolio: "https://dushyantrajotia.netlify.app/",
      bio: "AI/ML-focused developer with project experience in deep learning, model evaluation, and deployment-backed software builds.",
      highlights: [
        "Data Science Intern on Brain Tumor Classification (VGG19)",
        "Stock Market Analysis Tool internship project",
        "Built and deployed ML solutions with Streamlit and API-first workflow",
        "Sergeant in NCC with leadership and team coordination experience",
      ],
      skills: ["Machine Learning", "Deep Learning", "EDA", "NLP", "TensorFlow", "Scikit-Learn", "OpenCV", "Docker", "Web Development", "Android"],
      achievements: [
        "Academic Excellence Award (1st Year)",
        "2nd Position - Inter Group Competition of Idea and Innovation 2025",
      ],
      coursework: ["Machine Learning", "Deep Learning", "Statistics for ML", "Image Processing"],
    },
    {
      name: "Manul Sahu",
      role: "Developer",
      image: "m.png",
      email: "manulsahu3@gmail.com",
      phone: "+91 7015887332",
      linkedin: "https://www.linkedin.com/in/manul-sahu-764986354/",
      github: "https://github.com/manulsahu",
      portfolio: "",
      bio: "Developer focused on applied AI/ML systems, data analysis workflows, and hackathon-ready product development.",
      highlights: [
        "Data Science Intern on Brain Tumor Classification (VGG19)",
        "Built stock analysis and visualization tooling",
        "R&D Department contributor at E-Cell, CT University",
        "Hackathon finalist with strong MVP execution approach",
      ],
      skills: ["Machine Learning", "Deep Learning", "EDA", "NLP", "TensorFlow", "Scikit-Learn", "FastAPI", "Docker", "Web Development", "Android"],
      achievements: [
        "Academic Excellence Award (1st Year)",
        "Top 10 Finalist - TechForge Hackathon (LPU)",
      ],
      coursework: ["Machine Learning", "Deep Learning", "Statistics for ML", "Remote Sensing Applications"],
    },
  ],
  projects: [
    {
      name: "MovieLens",
      category: "AI / App",
      about: "A movie-focused product concept with recommendation direction and scalable app-ready structure.",
      features: ["GitHub repository available", "Can include Android APK", "Live demo slot ready"],
      liveUrl: "",
      repoUrl: "https://github.com/DevFusionOrg/MovieLens.git",
      apkUrl: "",
    },
    {
      name: "Duet",
      category: "Software / App",
      about: "A product build focused on collaborative workflow, clean structure, and practical extensibility.",
      features: ["Repository available", "Structured for future features", "Live preview can be attached"],
      liveUrl: "",
      repoUrl: "https://github.com/DevFusionOrg/duet.git",
      apkUrl: "",
    },
    {
      name: "BarterX",
      category: "Web / Marketplace",
      about: "A marketplace concept oriented around simple exchange flows and startup-style product delivery.",
      features: ["Repository available", "APK slot can be attached", "Demo-ready project structure"],
      liveUrl: "",
      repoUrl: "https://github.com/DevFusionOrg/BarterX.git",
      apkUrl: "",
    },
  ],
  faqs: [
    {
      question: "What does DevFusion specialize in?",
      answer: "DevFusion primarily focuses on AI, machine learning, and deep learning projects, and also ships web, Android, and software builds.",
    },
    {
      question: "Do you build only AI projects?",
      answer: "No. Along with AI and ML work, we build hackathon MVPs, Android applications, and web development projects for practical use.",
    },
    {
      question: "Can I hire DevFusion for a custom project?",
      answer: "Yes. Use the Work With Us form and share your scope, timeline, and budget. The team responds through devfusionorg@gmail.com.",
    },
    {
      question: "Will project links and APK links be updated over time?",
      answer: "Yes. The site data structure is built to add more projects, live demos, and direct APK download links later.",
    },
    {
      question: "What technologies do you commonly use?",
      answer: "Python, TensorFlow, Scikit-Learn, OpenCV, FastAPI, Docker, Android stack, and modern web development tooling.",
    },
  ],
};